// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// loco_c
arma::mat loco_c(const arma::mat& X, const arma::vec& y, Function mean_fun, int n_train);
RcppExport SEXP _loco_loco_c(SEXP XSEXP, SEXP ySEXP, SEXP mean_funSEXP, SEXP n_trainSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Function >::type mean_fun(mean_funSEXP);
    Rcpp::traits::input_parameter< int >::type n_train(n_trainSEXP);
    rcpp_result_gen = Rcpp::wrap(loco_c(X, y, mean_fun, n_train));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_loco_loco_c", (DL_FUNC) &_loco_loco_c, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_loco(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
