# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loco_c <- function(X, y, mean_fun, predict_fun, n_train) {
    .Call(`_loco_loco_c`, X, y, mean_fun, predict_fun, n_train)
}

